services:
  - type: web
    name: seu-app
    env: python
    # 👇 Altere a linha do buildCommand para esta:
    buildCommand: "mise settings set python_compile 1 && mise install && mise exec -- pip install -r requirements.txt"
    # O comando de start também deve usar o mise para garantir que está executando com a versão correta do Python
    startCommand: "mise exec -- gunicorn app:app"
